### ISSUE TITLE
[FR] F-Droid release

### ISSUE THREAD

**Issue by MisterrrX** [giejay/Immich-Android-TV#13]
**Is your feature request related to a problem? Please describe.**
I don't like using the Play Store (or Android-TV derivatives) and really appreciated that the Immich mobile app is available on the free software app store F-Droid.
Additionally, different storefronts, like the Fire-TV app store, don't offer all apps available in the Play Store.

**Describe the solution you'd like**
Release the client on F-Droid, similar to the main app.

**Comment by giejay** [comment]
Just tried to release it to FDroid but I'm using for example Firebase to record exceptions and that seems to be not allowed. So for now, you will have to manage with the releases page where you can find the latest apk.

**Comment by MisterrrX** [comment]
Well that makes sense, I thought your app was free software, sorry for the confusion. Thanks for the effort though.

**Comment by giejay** [comment]
Yeah, it's completely free, but FDroid does not allow any Google* libraries in an app. That would be quite a refactor for me to remove them all so for now, I will not focus on an FDroid release.
