### ISSUE TITLE
[BUG] Set Screensaver doenst apply

### ISSUE THREAD

**Issue by MaBeniu** [giejay/Immich-Android-TV#2]
I am new user to immich. running latest version 1.93.3 on proxmox docker compose. Android OS 12 TV and Immich app version 1.13. server connection via http://localIP. albums load fine as well no issues with video playback.
The only bug I noticed I am not able to use screensaver mode which is very interesting feature for me.

1. Go to menu
2. Click on Set screensaver
3. Navigate Home
4. press back button that enables screensaver. default google screensaver still running

p.s. that would also be awesome to see full library to scroll through with the family.

overall very positive with the app :)

**Comment by giejay** [comment]
Hi, you should see an Android native screen when pressing "set screensaver". That is not happening? Can you find a screensaver setting somewhere in the settings of your android tv box?

**Comment by MaBeniu** [comment]
Could it be that googleTV function ambient mode disables screensaver option?
No popup after toggling the function.
![1706439253587371383425233130160](https://github.com/giejay/Immich-Android-TV/assets/107912005/e1cc8737-a446-4183-a1d9-cf7ad8ad12eb)

**Comment by giejay** [comment]
Yes, the Ambient mode replaces the Screensaver option in the settings. But for my Sony Bravia with Android TV, I am able to open the "original" screensaver setting screen. 

Can you try: adb shell settings put secure screensaver_components nl.giejay.android.tv.immich/.playback.ScreenSaverService

**Comment by MaBeniu** [comment]
Nice, nice, nice
worked :)

**Comment by giejay** [comment]
Nice! Its a shame its a rather technical/difficult workaround, but I guess they completely removed the intent/activity for setting the screensaver in your Android version. 

But now you can try 1.14 and the option to select albums to use in the Screensaver:)

**Comment by MaBeniu** [comment]
> Nice! Its a shame its a rather technical/difficult workaround, but I guess they completely removed the intent/activity for setting the screensaver in your Android version.
I hope they will not go further with it and override it to default on each reboot. atm it works even after reboot.
Just curious such manipulation as I did via adb is not achievable within app permissions?

**Comment by giejay** [comment]
I'm afraid not. Adb is not installed by default and I'm not sure if there's another way

**Comment by giejay** [comment]
I will close this one and make a FAQ section in the readme.
