### ISSUE TITLE
Video glitching

### ISSUE THREAD

**Issue by Spicyballs02** [giejay/Immich-Android-TV#20]
Video glitching after watching 100+ photos and videos via screensaver, this glitching is the showing up on other apps on the to such as Netflix and also bbc iPlayer. Never happened before but has the 2 times I let the Immich screensaver run for a while.
Many of the landscape videos are also shown in portrait and very squished

**To Reproduce**
1. Watch screensaver with videos
2. Wait for glitch
3. Go to other apps and glitch will also appear
4. Reboot tv to fix 

![image](https://github.com/giejay/Immich-Android-TV/assets/161889603/5e834a2d-ebd6-4444-9a98-046cfd74d3ba)

 - Android OS version:  not sure will check
 - Device: Sony TV with android
 - Immich app version 1.100

**Comment by giejay** [comment]
So it only happens when watching videos? If you have an album with just photos, it doesnt occur?

**Comment by Spicyballs02** [comment]
> So it only happens when watching videos? If you have an album with just photos, it doesnt occur?

I haven’t checked an album with photos only as I have videos in all my albums. 
it had affected all apps and the only way to stop it was to remove the app (wife and kids were complaining too much)

**Comment by giejay** [comment]
Please re-open if you are still having issues with latest versions.
