### ISSUE TITLE
[FR] Projectivy Wallpaper Provider

### ISSUE THREAD

**Issue by Nixon506E** [giejay/Immich-Android-TV#24]
**Is your feature request related to a problem? Please describe.**
I would love if I could have my photos available to use as a Projectivy Launcher wallpaper provider.

**Describe the solution you'd like**
Would need to implement the code following the repo below:

https://github.com/spocky/projectivy-plugin-wallpaper-provider

Would be great to have the UI ability to set specific albums similar to how screensavers are set. Could use the same settings initially.

**Additional context**
Projectivy Launcher: https://play.google.com/store/apps/details?id=com.spocky.projengmenu

**Comment by MahmoudAlyuDeen** [comment]
+1

Very cool of projectivity to allow people to build plugins, even though the main project isn't open source.

Any idea of such existing wallpaper providers? 🤔

**Comment by ISeeTWizard** [comment]
Hi, stupid question maybe as I‘m new to Projectivity Launcher but isn‘t the option to choose a folder as source for the wallpaper exactly that what you are requesting?

**Comment by giejay** [comment]
This is a completely different approach then using this app I guess. Maybe its possible to re-use some parts of the ApiClient but other than that, I don't see any relation to this project.

**Comment by giejay** [comment]
I'm gonna close this since I will focus mainly on the Android TV app implementation, I guess/hope opening an issue at the projectivity wallpaper project is more likely to be succesful
