### ISSUE TITLE
[BUG] Please help update the icon

### ISSUE THREAD

**Issue by alextran1502** [giejay/Immich-Android-TV#26]
Hello, Alex from Immich here!

Can you help us update the icon used in the app? We've added the [Community Projects](https://immich.app/docs/community-projects) page on the website, and it would be great to use a different icon to distinguish community app from the official app on the app store

Thanks,
Alex

**Comment by giejay** [comment]
Hi, which icon should I use? I can't find the "community icons"

**Comment by alextran1502** [comment]
Hello, any icon that is different from the official icon would help.

**Comment by bo0tzz** [comment]
@giejay the issue is that with the name and logo you're using in the Play store, this ends up looking like an official project. We'd like to have a clearer distinction there.

**Comment by giejay** [comment]
I will change the title of the app in the play store and add a disclaimer on top of the description.

**Comment by bo0tzz** [comment]
Hi @giejay, I don't think the store page has changed yet and some users are still getting confused. Consider this a reminder :)

**Comment by giejay** [comment]
Google keeps on rejecting my updates because of strange feedback. I might just pull the entire project from the Play Store if this latest update is still not accepted

**Comment by alextran1502** [comment]
@giejay Anything we can do to help?

**Comment by giejay** [comment]
I have emailed Google for an explanation. This is the issue Im facing: https://support.google.com/googleplay/android-developer/thread/270001289/android-tv-app-rejected-with-reason-no-full-size-app-banner-and-or-icon?hl=en

Seems like a recent issue for more users

**Comment by bo0tzz** [comment]
Hey, the project is still up on the play store with the icon and name that confuse people into thinking it's official. Please change this like we requested.

**Comment by giejay** [comment]
Hi, I have adapted the name of the application in the play store.

**Comment by bo0tzz** [comment]
Perfect, thank you very much!
