### ISSUE TITLE
[FR] Show latest / random photos instead of only albums

### ISSUE THREAD

**Issue by martynvdijke** [giejay/Immich-Android-TV#27]
It would be really nice of there would be a toggle to show the latest X amount of photos instead of only showing photos that belong to a album. 
Or maybe even randomly cycling trough all photos instead of only albums.

**Comment by giejay** [comment]
I will check if I can make this work

**Comment by genotrance** [comment]
I would like this too - I don't care to make albums and would rather see all photos. In fact, Immich also has folder views which negates the need for albums.

**Comment by giejay** [comment]
I made the changes for the screensaver (latest, random, seasonal), I will include this as a new Tab in the app itself as well.

**Comment by giejay** [comment]
Latest release includes tabs like Random, Seasonal, Recent and People
