### ISSUE TITLE
[BUG possible?] Can not play videos on SONY TV

### ISSUE THREAD

**Issue by kevinshane** [giejay/Immich-Android-TV#32]
**Describe the bug**
All videos seems not playing at all. Including .MOV .mp4 format.
All videos are transcoded to mp4 but still can't play at all. But on a iPhone, or Android phone(s21u), or web browser, they are working.

Do you guys having the same problems?

**Comment by giejay** [comment]
I have a Sony Bravia Android TV as well and no issues for me

**Comment by giejay** [comment]
Not reproduceable
