### ISSUE TITLE
[BUG] can’t disable video or audio playback in screensaver

### ISSUE THREAD

**Issue by ianschmitz** [giejay/Immich-Android-TV#33]
**Describe the bug**
Disabling video playback or audio in screensaver settings does not take effect. 

**To Reproduce**
1. Go to screensaver settings
2. Turn off video playback and audio
3. Trigger screensaver
4. Observe videos still play with audio

**Expected behavior**
Settings should be respected.

**My setup (please complete the following information):**
 - Android OS version: 11
 - Device: Nvidia Shield Pro
 - Immich app version [e.g. 1.10]: 1.34

**Comment by giejay** [comment]
This is still a work in progress, see the table in the readme. You should even see a message: Work in progress when clicking it

**Comment by MahmoudAlyuDeen** [comment]
WIP is shows, but we can't disable the feature, videos play with audio even if the feature is off

**Comment by giejay** [comment]
That's because it was work in progress;) But in the latest release this should be fixed
