### ISSUE TITLE
New Immich Release v1.106.1  Error Message ' Invalid status code from API:404

### ISSUE THREAD

**Issue by Philshappy** [giejay/Immich-Android-TV#36]
Installed update of Immich version to v1.106.1
Tried to use Immich-Android-TV app
Failed API
Created new Immich API code
Updated Immich-Android-TV app API code under setting (Nvidia Shield)
Does not open Albums or Photos, Error message 'Invalid status code from API:404'

**Comment by ianschmitz** [comment]
Release reference: https://github.com/immich-app/immich/releases/tag/v1.106.1

**Comment by giejay** [comment]
Fixed: https://github.com/giejay/Immich-Android-TV/releases/tag/1.35
