### ISSUE TITLE
[BUG] Almost impossible to play Videos in 4k

### ISSUE THREAD

**Issue by commanderalpha** [giejay/Immich-Android-TV#37]
**Describe the bug**
I want to play videos that have a higher resolution. Like 4k.
The Video player stuck after a few seconds, may it loads the next seconds but most of the time the app then crashes.
Its also hard to get back or jump to the next picture. App is not responding in this case.

Video filmed on Galaxy S20 in 4k 30fps h.264 mp4

No Problem with FHD videos

**To Reproduce**
Play video in higher resolution

**Expected behavior**
Smooth playback

**Screenshots**
should be not necessary

**My setup (please complete the following information):**
 - Android OS version: the actual on for the Device
 - Device: Nvidia Shield Pro
 - Immich app version: 1.34 ,Server 1.105.1

**Additional context**
-

**Comment by Squ1dw4rd99** [comment]
same problem here, setup:
+ v1.35 (sideloaded)
+ NVIDIA Shield Pro
+ videos that cause problems are for example 4K HDR (Dolby Vision) HEVC (.mov) files recorded with an iPhone 13

**Comment by giejay** [comment]
Could you upload an example here: https://giejay-immich.duckdns.org/share/2qm6QJBSeH3fQ1g5BYzCf6kakDkFYD5NquHdK_jNqmSWLK9qA1G1eqfqNWksGMBj2nI

**Comment by Orofire** [comment]
Hello,
I have the exact same issue with any video in 4K.
The thread is marked as completed but didn’t find the solution/workaroud.
Immich TV version : 2.5.0
Device : shield pro
Immich server version : 1.125.2
Server : ubuntu server (Docker)

Thanks,

**Comment by giejay** [comment]
Hi, same request for you, could you upload a test video here: https://giejay-immich.duckdns.org/share/jDXi6rXibGhzK7cVJ8rpUiZZ6L5id051fl7zj4jcKaZTmHZxQtSS7Iqbu6ASXa4u8GE

password: testing
