### ISSUE TITLE
[FR] Kodi app

### ISSUE THREAD

**Issue by lmgithu** [giejay/Immich-Android-TV#39]
**Is your feature request related to a problem? Please describe.**
It is not related to any problems.

**Describe the solution you'd like**
Kodi / OSMC is one of the most popular, open source media player for TVs. I think it would be great and relatively easy to launch your app as an Addon on that platform as well.

**Comment by giejay** [comment]
I will not work on this since I don't use Kodi and don't see a real benefit instead of just launching it from Android TV launcher.
