### ISSUE TITLE
[BUG] Cannot login to my Immich server

### ISSUE THREAD

**Issue by andrzej-r** [giejay/Immich-Android-TV#4]
**Describe the bug**
"Please enter a valid host name and API key." after providing both. I tried both external https reverse proxy and http://ip:3001 addresses. Triple checked the API key, although entering it by hand is not ideal.

**Screenshots**

**My setup (please complete the following information):**
 - Android OS version: 9
 - Device: Sony Bravia TV
 - Immich app version: 1.16

**Comment by giejay** [comment]
The demo mode does work for you? The only check thats being done, is the hostname, whether it's a valid url. I will release a new version which specifies which part of the input is invalid.

**Comment by orsa86** [comment]
I've same issue. Double checked API key and tried different formats for hostname, but nothing worked. What should be valid format for hostname? I presume `http://ip_address:port`.

**Comment by andrzej-r** [comment]
Demo mode works fine here.

Host names I tried were:
https://public.domain.name (served via a Caddy reverse proxy)
http://192.168.1.2:3001

Both are accessible via a browser or the Android Immich app.

**Comment by OGTK423** [comment]
I am currently experiencing a similar issue. I have correctly entered my host URL (including HTTP and port) as well as the API key (which I have confirmed to be entered accurately) and get presented with a "Could not fetch items! Status code: 401" error.

**Comment by giejay** [comment]
It might be an issue with the API key not being saved in the description/input field correctly. I was able to reproduce it, highlighting the field again and pressing enter/ok will save it. I will try to fix it properly but for now, I adjusted the error message to reflect these steps.

**Comment by andrzej-r** [comment]
I've upgraded the app to version 1.18.1 - it was indeed complaining about the hostname. I was able to "fix" it by selecting the field with my remote and pressing a "back" button on it.

So, the problem was with entering the hostname via an attached keyboard. Pressing "enter" does not register the text typed into the field. However, I am unable to use just the remote itself - I can navigate the field with left/right/back buttons but there is no way to enter the text with the remote (no virtual keyboard available).

I tried following the same method for typing the API key (first with the attached keyboard, then register it with the remote) but the result is always the same: 401 error when accessing photos or albums and no content visible. I used a freshly generated API key of a new user added to Immich.

**Comment by giejay** [comment]
If you don't see a message: enter an API key, that means your API key is
valid or at least saved correctly.

I suggest to use the Google TV or Android TV app on your phone to enter the
API key, then you can copy it, instead of typing it.

**Comment by andrzej-r** [comment]
Copying a newly generated API key from a browser worked, so it was either a typo (very likely, despite me checking it several times) or, like with the hostname, it had something to do with me using an attached physical keyboard.

The overall experience of logging in could be improved.

Closing this ticket as the issue I reported is now solved.

**Comment by giejay** [comment]
Nice! FYI, I found a way to always save the input succesfully, also when hardware keyboards are used. Will be available in the next release.
