### ISSUE TITLE
Released V1.35 Not Available

### ISSUE THREAD

**Issue by Philshappy** [giejay/Immich-Android-TV#40]
Although V1.35 is the latest release it is not available as an update.

**Comment by giejay** [comment]
Correct, it got rejected because of some issue with the demo environment. Fixed now and v1.35.1 is being reevaluated.

**Comment by dariuszszyc** [comment]
why not always add .apk to the releases ?

**Comment by giejay** [comment]
Apks are also added here for every commit: https://github.com/giejay/Immich-Android-TV/actions

Or feel free to build the app yourself

**Comment by dariuszszyc** [comment]
> Apks are also added here for every commit: https://github.com/giejay/Immich-Android-TV/actions
> 
> Or feel free to build the app yourself

Thank you !
It may sound funny but I wasn't aware that those are available for every commit

**Comment by giejay** [comment]
No problem, it is pretty hidden indeed. Might add a link to the readme.
Especially now when Google is rejecting my app for some strange quality
reason...

**Comment by dariuszszyc** [comment]
FYI, I tried installing that APK and got message that it couldn't be done because the package doesn't seem to be correct.
It did recognize the app as it asked me to update the current one.
Even when I removed the one installed already on Android TV - I couldn't install it for the same reason.
I don't know if it's the fact it's unsigned or something else. I'm not a pro in those matters.

**Comment by jay-oswald** [comment]
@giejay I still can only get to `1.34` is `1.35.1` close to getting passed?

**Comment by giejay** [comment]
No, Google is rejecting it for strange and various reasons..I'm now doing a final attempt and otherwise I'm just gonna delete it from the Play store. I would just sideload it if I where you

**Comment by sravanivundavalli** [comment]
Hi @giejay, first of all, great work.

I get "App not installed as package appears to be invalid" when trying to install the apk downloaded from actions. 

I uninstalled the app downloaded from playstore before trying to install this apk file.

**Comment by giejay** [comment]
And from the releases page? That should be the official APK which also gets uploaded to Google
