### ISSUE TITLE
Google Play Store 404

### ISSUE THREAD

**Issue by MadWalnut** [giejay/Immich-Android-TV#41]
The Google Play Store URL 404s for me: https://play.google.com/store/apps/details?id=nl.giejay.android.tv.immich

I also cannot find the app via search. Has Google taken it offline?

**Comment by MadWalnut** [comment]
I see, unfortunate move from Google... I will sideload then for now, it's really easy over adb anyways. I just prefer the Play Store release due to automatic updates. You can close the issue or keep it open, as you wish. Thanks for your work!

**Comment by ramapullareddyc** [comment]
I am getting some crashes when playing video in android tv stick. Let me know what logs to share if it helps. No issued with browsing photos.

**Comment by davralin** [comment]
> I have taken it offline.

I see the frustration here, but do you any plans to re-add it at a later point?

With the rapid development of immich, I'm a bit hessitant to deploy something that I have to manually update every time on remote TV's with my relatives.

**Comment by giejay** [comment]
No plans in the foreseeable future

Op wo 31 jul 2024 om 14:44 schreef davralin ***@***.***>:

**Comment by giejay** [comment]
After the 2 merge requests, Im attempting to give it one more go. Let's hope they don't reject it this time

**Comment by carlosjfcasero** [comment]
Any updates on this?

**Comment by giejay** [comment]
It's back!
