### ISSUE TITLE
[BUG] Error 403

### ISSUE THREAD

**Issue by MadWalnut** [giejay/Immich-Android-TV#42]
**Describe the bug**
I cannot load any images or albums in the app. I receive the error `Invalid status code from API: 403, make sure you are using the latest Immich server release.` I tried clearing app data and logging in again but that did not help.

**To Reproduce**
1. Open the app
2. See error

**Expected behavior**
Images should load

**My setup (please complete the following information):**
 - Android OS version: 12
 - Device: Chromecast with Google TV (4K)
 - Immich app version 1.36.1 (the newest GitHub release is 1.35, but this is what Android shows me)
 - Immich server version: 1.107.2

**Comment by ramapullareddyc** [comment]
I had same issue with app installed from Play store. I tried installing APK downloaded from GitHub release page which seems to be working fine

**Comment by MadWalnut** [comment]
Due to #41 I already have the app installed via GitHub APK, but thanks for the suggestion.

It seems to have fixed itself, maybe with a recent Immich update? I will close for now.
