### ISSUE TITLE
Black background instead of grey.

### ISSUE THREAD

**Issue by OMMJAI** [giejay/Immich-Android-TV#45]
**Is your feature request related to a problem? Please describe.**
I'm really enjoying the app and am eager to see EXIF data displayed on the screen. However, I'm puzzled as to why the background adjacent to images is grey instead of black.

**Describe the solution you'd like**
I would prefer an option for a black background.

**Comment by MahmoudAlyuDeen** [comment]
I second that, black works way better on OLED screens

**Comment by giejay** [comment]
Will be added in the next release
