### ISSUE TITLE
[BUG] Video streched

### ISSUE THREAD

**Issue by devtechk** [giejay/Immich-Android-TV#47]
**Describe the bug**
Some videos are shown stretched I grab them by my iphone in portrait mode.

**To Reproduce**
Just reproduce a video grabbed from iphone 

**Expected behavior**
Video not streched but shown in protrait mode, depends on it was grabbed.

**My setup (please complete the following information):**
 - Android OS version: 
 - Device: Fire Tv last os
 - Immich app version last release

**Additional context**

**Comment by giejay** [comment]
https://github.com/giejay/Immich-Android-TV/issues/7
