### ISSUE TITLE
[BUG] Possible conflict with Youtube app

### ISSUE THREAD

**Issue by andrzej-r** [giejay/Immich-Android-TV#5]
**Describe the bug**
I do not know if this is related but after starting the Immich Android TV app and switching to the Youtube app, YT app freezes. 

**To Reproduce**
1. Start Immich Android TV (I used the demo mode)
2. Exit to the home Android TV screen
3. Start Youtube app and wait several seconds
4. Youtube app stops responding to the user inputs (remote controller or keyboard). Forcefully closing YT app does not help. Restarting the TV helps until the next time Immich app is started again. So far I was able reproduce this issue every time and I have not seen it before installing the Immich app.

**My setup (please complete the following information):**
 - Android OS version: 9
 - Device: Sony Bravia
 - Immich app version: 1.16

**Comment by hasecilu** [comment]
I tried on TCL TV with Beyond OS but couldn't reproduce problem. Immich TV v 1.17.
Maybe you could be interested on: [SmartTube](https://github.com/yuliskov/SmartTube) to avoid a sub-optimal experience and also test if that also occurs.

**Comment by andrzej-r** [comment]
I have not been able to reproduce this issue after upgrading to 1.18.1 (only tested switching from Immich to YT twice but before it happened every time). However, at one point my Android TV has restarted during/after watching several videos. This is just speculation but could it be a memory leak?

I cannot reproduce this issue with SmartTube either.

**Comment by giejay** [comment]
I will do some investigation if there could be memory issues
