### ISSUE TITLE
Can I use this to get Immich onto my Amazon Fire TV Stick?

### ISSUE THREAD

**Issue by temal32** [giejay/Immich-Android-TV#50]
Hello,

I have an Amazon Fire TV Stick in my TV, I bought the stick because my TV has no internet access so I use the Amazon stick to watch Netflx, Disney, etc.. on my TV. My question is, can I use this repo to get Immich client on my Fire TV Stick?

**Comment by giejay** [comment]
Yes, just sideload it using the APK from the releases page here on GitHub

**Comment by sorryusernameisalreadytaken** [comment]
@temal32 as already mentioned you need to sideload the apk. Just search in the internet something like 'sideload apk firetv'. You should get 1000 of results.
Please use in future the github issue for issues and the [discussions area](https://github.com/giejay/Immich-Android-TV/discussions) for questions like this.

@giejay can you move this issue?
