### ISSUE TITLE
ScreenSaver on FireStick 4k Max

### ISSUE THREAD

**Issue by juanpeich** [giejay/Immich-Android-TV#53]
Thank you very much for such a valuable project.

I'm trying to put the screensaver on Fire Stik 4k Max. I have developer and debugging options enabled on FireStick.

The problem is that I think that to install the adb drivers you have to connect the devices via USB to the computer. I can't access firestick from the folder, through terminal, typing "adb connect 192.168.xxx.xxx"

You could help me.

Thank you very much in advance

**Comment by giejay** [comment]
Did you enable ADB debugging?

**Comment by juanpeich** [comment]
> Did you enable ADB debugging?

@giejay Yes, I have it enabled on FireStick. It's more like it doesn't recognize the command in the Windows 10 terminal "adb connect 192.168...." (running it inside the adb drivers folder)

**Comment by giejay** [comment]
When you run it inside the same folder the "adb" binary resides, it should just work. Try powershell or command prompt both
