### ISSUE TITLE
[BUG] Cannot install app on Android 13

### ISSUE THREAD

**Issue by lv913** [giejay/Immich-Android-TV#55]
**Describe the bug**
I cannot install app on Android 13. Google Play says that my mobile phone is not supported for installing the app.

**To Reproduce**
1. Go to Google Play.
2. Search for a mobile phone running Android 13.
3. A grey message saying "This element is not compatible with the device" will be displayed.

**Expected behavior**
I would expect to find my device in the list of the allowed devices.

**My setup (please complete the following information):**
 - Android OS version: 13
 - Device: Xiaomi Poco X4 Pro 5G
 - Immich app version [e.g. 1.10]: 1.115.0

**Comment by giejay** [comment]
This is for Android tv
