### ISSUE TITLE
[FR] Improve picture viewer, problem showing filenames

### ISSUE THREAD

**Issue by hasecilu** [giejay/Immich-Android-TV#6]
**Is your feature request related to a problem? Please describe.**

Sometimes the filename of the photos are meaningless (specially those names that Immich assigns when uploading a photo), or sometimes not very descriptive about the photo (like be named using the date). 

- Currently the viewer shows the filename at the top when no description is found. Some filenames are bad, feels noisy.
- When opening an album the labels that contain the filenames takes "a lot" of space and it looks like is not even alphabetically ordered (maybe by date of creation).
- When album background photo is white text is not readable.
- No album description
- When pressing `Back` key you left the viewer, a good behavior would be to hide the text.
- Columns of photos on album view are not exactly centered. When you move to right all columns moves a little to the left because there is no margin on the right.

**Describe the solution you'd like**

- [x] Don't show filename when no description exists, better nothing than _dirty_ filenames. Moving at the bottom seems more sensible than in the top because some descriptions are long.
- [ ] To make labels take less space, maybe create a transparent label over the photos
- [ ] Hide the text when pressing `Back` key, press again and exit the image viewer.
- [ ] Add album description
- [ ] Better contrast on album name, maybe transparent background (like in the image viewer) or black border on letters.
- [x] Fix margins/photo/column size on album view.

**Additional context**
Maybe the Jellyfin image viewer can give some ideas.
Tested v1.17

**Comment by giejay** [comment]
Thanks for the extensive feedback! I will do a big overhaul of the viewer once the MVP features are (mostly) bug free. That includes showing the EXIF data (probably on the right, with a toggle), just like on the webview. And showing a bar on the bottom similar to this: 

<img width="966" alt="image" src="https://github.com/giejay/Immich-Android-TV/assets/2014373/de7d8860-922d-4dec-98ed-e7de71e712bf">

Indeed when pressing back, the bottom bar should first disappear like in other popular video players. 

Your last point, I will fix in a next release.

**Comment by hasecilu** [comment]
Thanks! I think it was already mentioned on the Immich discussion, apart from Albums, having the **Photos** (timeline) and **People** sections would be nice.

**Comment by kaiwei** [comment]
Is it also possible to (optionally) load the (already) generated thumbnail first, and then the actual if lingering for more than [X] seconds, i.e. the same behavior as the mobile app as it stands? Reason for said request is because some of the raw image / video files are very large, and the app basically freezes while trying to load them over the network.

**Comment by giejay** [comment]
> Is it also possible to (optionally) load the (already) generated thumbnail first, and then the actual if lingering for more than [X] seconds, i.e. the same behavior as the mobile app as it stands? Reason for said request is because some of the raw image / video files are very large, and the app basically freezes while trying to load them over the network.

I have added thumbnail loading in release 1.21. Will be available within a few hours.

**Comment by LesKent** [comment]
It would be great to have an option to display only the Album name with the image. Often file names are not very useful and automatically generated in sequential order by the camera unless someone does a lot of manual work.

**Comment by giejay** [comment]
Most of the stuff mentioned in the OP are implemented now. If you are missing anything specific, feel free to open a FR
