### ISSUE TITLE
[BUG] Immich v1.119.1 getting API 401 Error

### ISSUE THREAD

**Issue by MattFaz** [giejay/Immich-Android-TV#62]
**Describe the bug**
Latest version of Immich v1.119.1 is causing app to get a 401 error when trying to view photos or albums.

**To Reproduce**
1. Instal app on android tv
2. Update Immich to v1.119.1
3. Attempt to view photos or albums

**Expected behavior**
View Albums and Photos

**My setup:**
 - Android TV OS version: 10 (01 April 2024)
 - Device: Sony Bravia VH1
 - Immich app version: 1.119.1

**Comment by giejay** [comment]
Just tried it myself using the Demo version and my own Immich instance, both hosting server version 1.120.1. Working fine for me. Does the demo work for you?

**Comment by frostworx** [comment]
Hi,

I recently migrated to immich and shortly after found your Android TV app (so no experience with previous versions).

I'm not sure if I did something wrong on my end _(e.g. mix up `I`and `l` or `0` and `O` while tying in the API key)_,
but I can confirm the 401 error on my Nvidia Shield.
The demo mode works just fine.

**Comment by giejay** [comment]
If the demo mode works fine, it's your API key. Use an android mobile app like Google TV to enter the key instead of manually using your remote.

**Comment by frostworx** [comment]
thanks a lot, thought so :)
