### ISSUE TITLE
[FR] Side-by-side portrait pictures during screensaver mode

### ISSUE THREAD

**Issue by Foshkey** [giejay/Immich-Android-TV#66]
**Is your feature request related to a problem? Please describe.**
When I have Google photos as the screensaver, it'll put 2 portrait photos side-by-side instead of just 1 in the center, which I like better.

**Describe the solution you'd like**
The option to have portrait photos side-by-side in the screensaver mode.

**Additional context**
I think Google Photos selects 2 portrait photos based on some sort of similarity? Like I often see two photos from the same photo shoot or two cat pics, or something.

However, if that's too much effort, then I don't mind not having that feature. I think just another random portrait photo from the same album could work 😄

**Comment by giejay** [comment]
I'll give this some thought. A bit challenging but in the first iteration I might be able to merge 2 photos which would be shown after eachother

**Comment by giejay** [comment]
Implemented in version 2.0. By default enabled to merge 2 portrait photo's in screensaver and in regular viewer. In regular mode, it only merges them when 2 portraits would be shown after each other.

**Comment by Foshkey** [comment]
I noticed this last week and forgot to say thank you!! Seems to be working great, I really appreciate it!
