### ISSUE TITLE
Screensaver of "Recent Pictures" or "All Pictures" or "similar seasons"

### ISSUE THREAD

**Issue by nreeb** [giejay/Immich-Android-TV#67]
**Is your feature request related to a problem? Please describe.**
Right now you can only select a screen saver to use albums

**Describe the solution you'd like**
The ability to select "Recent images", "all images", "similar time period" would be nice. 

Recent Images - would set your screen saver to randomly show recent images randomly. As it went through them it could add to the list to show. 

All images - would set your screen saver to randomly go through all images 

Similar time Period - show images from this season as well as past seasons. I e. Current month and previous years in that month so in the summer, fall, Christmas, Halloween etc you would get random pictures from that season and past seasons to reminisce over

**Additional context**

**Comment by giejay** [comment]
I like this and so does the wife, so implemented it in 1.42: https://github.com/giejay/Immich-Android-TV/releases/tag/1.42

Can you give it a try? I will upload it in the play store somewhere this week.

**Comment by giejay** [comment]
Released

**Comment by nreeb** [comment]
Looks like it is working great! The only thing I am wondering because I have not watched it long enough is do you include the current season in the seasonal ones. I.E. Will you get 2024 seasons in addition to all the other years?
