### ISSUE TITLE
[BUG] App not installable on recent Sony Bravia TV

### ISSUE THREAD

**Issue by pedropombeiro** [giejay/Immich-Android-TV#73]
**Describe the bug**

**To Reproduce**
1. Go to https://play.google.com/store/search?q=immich&c=apps
2. Click on `Choose a device`
4. See that app is not installable on device

**Expected behavior**

I'd expect the app to be installable, since I'm able to run it if I install the .apk
**Screenshots**

<img width="513" alt="image" src="https://github.com/user-attachments/assets/4cc257b3-13b0-40dc-bccc-d5b01e7b7060" />

**My setup (please complete the following information):**
 - Android OS version: 10
 - Device: Sony XR-65X95L
 - Immich app version [e.g. 1.10]

**Additional context**

**Comment by giejay** [comment]
You are installing the wrong version. Thats the android phone app, not created by me. You need this one: https://play.google.com/store/apps/details?id=nl.giejay.android.tv.immich&hl=nl

**Comment by pedropombeiro** [comment]
Doh, I clearly wasn't paying attention when I searched for the app on the Store. Thanks, confirmed that it installed fine 👍
