### ISSUE TITLE
[BUG] - Can't set Screensaver on Google TV

### ISSUE THREAD

**Issue by nreeb** [giejay/Immich-Android-TV#76]
**Describe the bug**
I have a Google TV when I go to set the Immich TV as the screensaver it gives me the popup to add the setting. I add the setting using adb and even do a list of the secure settings to verify it is there.

Each time I click to add the screensaver i get the Not Possible to set screensaver message

**To Reproduce**
1. Go to ScreenSaver
2. Click Set ScreenSaver
3. Observe the popup

**Expected behavior**
Immich TV would be set as screensaver

**Screenshots**

**My setup (please complete the following information):**
 - Android OS version: 12
 - Device: Google TV
 - Immich app version 1.22.3

**Additional context**

**Comment by nreeb** [comment]
Just a quick update. In the settings I saw a screensaver_default_component on the Google TV. I tried to set it instead of the one in your instructions. Actually I left them both. Anyway I now get your screensaver.

Still tells me it can't set it in the settings, but I am getting to see it now.

**Comment by giejay** [comment]
It is a bit tough to set it from the app itself but glad you got it to work!
