### ISSUE TITLE
[FR] "Time Period" settings for recent and seasonal

### ISSUE THREAD

**Issue by nreeb** [giejay/Immich-Android-TV#77]
**Describe the solution you'd like**
When you choose Seasonal or Recent it would nice to be able to have a setting that controls the time period. I have lots of thoughts on this but for example....

Recent - How far back should you consider recent? week, month, 10 days etc.
Seasonal - How many years should you go back, maybe forever, maybe 5? and in addition to that what is the season? 10 days on either side of today?

**Additional context**

**Comment by giejay** [comment]
This is implemented in release 2.1
