### ISSUE TITLE
ERR_SSL_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by rjgrandy** [giejay/Immich-Android-TV#79]
I set up IMMICH TV and it all worked well for a little while. However one day it started to show the ERR_SSL_PROTOCOL_ERROR screen when it tries to go into screensaver mode. The main app still works and pulls the photos. Any idea why this happens? And how to fix?

**Comment by giejay** [comment]
Can you send your user id? It's in the debug menu

**Comment by rjgrandy** [comment]
0d88e376-7a5d-470e-8d30-7942c36d4346

It is trying to use https when on the error screen in the screensaver, but the main app I set the hostname to use just http. Could that cause an issue?

**Comment by giejay** [comment]
I'm seeing this: failed to connect to /192.168.1.132 (port 2283) from /192.168.1.129 (port 51446) after 10000ms: isConnected failed: ECONNREFUSED (Connection refused) 

I don't see the https prefix (or http). Can you try setting it up again the server setting section?

**Comment by rjgrandy** [comment]
I deleted the data, cache, then reset up and now it seems to work.

**Comment by giejay** [comment]
Great!
