### ISSUE TITLE
Android TV Screensaver while Slideshow is on

### ISSUE THREAD

**Issue by brkdwn** [giejay/Immich-Android-TV#8]
**Describe the bug**
When a slideshow of an album is running, the android TV screensaver is activating.

**To Reproduce**
1. Go to album
2. Click on one album
3. Start the slideshow
4. Wait for the android tv screensaver

**Expected behavior**
Screen saver should be deactivated when slideshow mode is on

**My setup (please complete the following information):**
 - Android OS version: ?
 - Device: Xiaomi Box S
 - Immich app version 1.18?

**Comment by giejay** [comment]
Good find, I fixed it in release 1.19 which will be published in the play store in a few hours.
